### ISSUE TITLE
Author with multiple values loses first value

### ISSUE THREAD

**Issue by Sophist-UK** [berdario/mutagen#1]
I have not quite worked out how to fix this (hence an issue rather than a PR) but...

According to https://msdn.microsoft.com/en-gb/library/windows/desktop/dd743065(v=vs.85).aspx the Author tag in an ASF file can have multiple values however unlike all other multiple value tags, Author is also in the basic Content Descriptor Object.

There appears to be an issue in handling putting the first value in the basic CDO and the subsequent values in the ECDO and then loading them back in again - and the first item is lost.

So `ASFFile.tags['Author'] = ['Artist1', 'Artist2', 'Artist3']` when saved and reloaded results in 'ASFFile.tags['Author'] == ['Artist2', 'Artist3']`.

**Comment by Sophist-UK** [comment]
Apologies - not a bug in mutagen but in my calling code.

**Comment by berdario** [comment]
Hi, good that you found a solution, but just as note:

This project is my porting effort from 2012/2013. It should work, but it hasn't really been touched since

There's another project from 2013/2014: https://github.com/LordSputnik/mutagen and its developer has since got access to the main mutagen repository to contribute on that.

The main repository is at:

https://bitbucket.org/lazka/mutagen

So, you might be better off contacting these sources, rather than me (since I don't really have any vested interest in mutagen)

I'll see to update the README accordingly now, and maybe disable the github issues. The description was already saying:

> Porting to Python3 of the mutagen library

btw, which implies that this is only a Porting of the original project
